-- Monster -> best usable area rune ID, auto-generated from monster lua files.
-- Vocation use restrictions sourced from data/scripts/runes/*.lua (not conjure scripts).
-- Only Holy Missile (3182) has a use restriction (paladin-only) so it is excluded.
-- All other area runes including Avalanche, Stone Shower etc have NO use restriction.
-- Rune IDs: 3161=Avalanche(ice) 3202=Thunderstorm(energy) 3191=GreatFireball(fire)
--           3175=StoneShower(earth) 3155=SuddenDeath(death) 3200=Explosion(physical)
monsterWeaknessRunes = {}
monsterWeaknessRunes["a carved stone tile"] = 3161
monsterWeaknessRunes["abyssador"] = 3200
monsterWeaknessRunes["abyssal calamary"] = 3202
monsterWeaknessRunes["achad"] = 3161
monsterWeaknessRunes["acid blob"] = 3202
monsterWeaknessRunes["acolyte of darkness"] = 3161
monsterWeaknessRunes["acolyte of the cult"] = 3202
monsterWeaknessRunes["adept of the cult"] = 3202
monsterWeaknessRunes["adult goanna"] = 3202
monsterWeaknessRunes["adventurer"] = 3161
monsterWeaknessRunes["afflicted strider"] = 3191
monsterWeaknessRunes["aftershock"] = 3175
monsterWeaknessRunes["aggressive lava"] = 3161
monsterWeaknessRunes["aggressive matter"] = 3161
monsterWeaknessRunes["agressive chicken"] = 3161
monsterWeaknessRunes["agrestic chicken"] = 3161
monsterWeaknessRunes["ahau"] = 3161
monsterWeaknessRunes["alchemist container"] = 3161
monsterWeaknessRunes["alptramun"] = 3191
monsterWeaknessRunes["amazon"] = 3155
monsterWeaknessRunes["amenef the burning"] = 3161
monsterWeaknessRunes["an astral glyph"] = 3202
monsterWeaknessRunes["an observer eye"] = 3175
monsterWeaknessRunes["ancient lion archer"] = 3161
monsterWeaknessRunes["ancient lion knight"] = 3155
monsterWeaknessRunes["ancient lion warlock"] = 3161
monsterWeaknessRunes["ancient scarab"] = 3191
monsterWeaknessRunes["ancient spawn of morgathla"] = 3161
monsterWeaknessRunes["angry adventurer"] = 3161
monsterWeaknessRunes["angry demon"] = 3161
monsterWeaknessRunes["angry plant"] = 3161
monsterWeaknessRunes["angry sugar fairy"] = 3175
monsterWeaknessRunes["animated clomp"] = 3161
monsterWeaknessRunes["animated cyclops"] = 3161
monsterWeaknessRunes["animated feather"] = 3191
monsterWeaknessRunes["animated guzzlemaw"] = 3161
monsterWeaknessRunes["animated moohtant"] = 3161
monsterWeaknessRunes["animated mummy"] = 3161
monsterWeaknessRunes["animated ogre brute"] = 3161
monsterWeaknessRunes["animated ogre savage"] = 3161
monsterWeaknessRunes["animated ogre shaman"] = 3161
monsterWeaknessRunes["animated rotworm"] = 3161
monsterWeaknessRunes["animated skunk"] = 3161
monsterWeaknessRunes["animated snowman"] = 3191
monsterWeaknessRunes["animated stone golem"] = 3161
monsterWeaknessRunes["animated stone rhino"] = 3175
monsterWeaknessRunes["animated sword"] = 3161
monsterWeaknessRunes["annihilon"] = 3191
monsterWeaknessRunes["anomaly"] = 3202
monsterWeaknessRunes["antenna"] = 3161
monsterWeaknessRunes["apocalypse"] = 3200
monsterWeaknessRunes["apprentice sheng"] = 3161
monsterWeaknessRunes["arachir the ancient one"] = 3191
monsterWeaknessRunes["arachnophobica"] = 3161
monsterWeaknessRunes["arbaziloth"] = 3202
monsterWeaknessRunes["arctic faun"] = 3191
monsterWeaknessRunes["armadile"] = 3191
monsterWeaknessRunes["armenius (creature)"] = 3161
monsterWeaknessRunes["ashmunrah"] = 3191
monsterWeaknessRunes["askarak demon"] = 3191
monsterWeaknessRunes["askarak lord"] = 3191
monsterWeaknessRunes["askarak prince"] = 3191
monsterWeaknessRunes["aspect of power"] = 3161
monsterWeaknessRunes["assassin"] = 3200
monsterWeaknessRunes["avalanche"] = 3202
monsterWeaknessRunes["axeitus headbanger"] = 3191
monsterWeaknessRunes["azerus"] = 3200
monsterWeaknessRunes["azure frog"] = 3191
monsterWeaknessRunes["badger"] = 3161
monsterWeaknessRunes["bakragore"] = 3161
monsterWeaknessRunes["baleful bunny"] = 3161
monsterWeaknessRunes["bandit"] = 3200
monsterWeaknessRunes["bane bringer"] = 3200
monsterWeaknessRunes["bane of light"] = 3202
monsterWeaknessRunes["banshee"] = 3161
monsterWeaknessRunes["barbaria"] = 3161
monsterWeaknessRunes["barbarian bloodwalker"] = 3155
monsterWeaknessRunes["barbarian brutetamer"] = 3200
monsterWeaknessRunes["barbarian headsplitter"] = 3175
monsterWeaknessRunes["barbarian skullhunter"] = 3175
monsterWeaknessRunes["barkless devotee"] = 3175
monsterWeaknessRunes["barkless fanatic"] = 3175
monsterWeaknessRunes["baron brute"] = 3161
monsterWeaknessRunes["bashmu"] = 3155
monsterWeaknessRunes["bat"] = 3175
monsterWeaknessRunes["battlemaster zunzu"] = 3155
monsterWeaknessRunes["bazir"] = 3161
monsterWeaknessRunes["bear"] = 3161
monsterWeaknessRunes["beast hulking prehemoth"] = 3202
monsterWeaknessRunes["behemoth"] = 3161
monsterWeaknessRunes["berserker chicken"] = 3200
monsterWeaknessRunes["betrayed wraith"] = 3200
monsterWeaknessRunes["bibby bloodbath"] = 3175
monsterWeaknessRunes["big boss trolliver"] = 3161
monsterWeaknessRunes["biting book"] = 3161
monsterWeaknessRunes["biting cold"] = 3161
monsterWeaknessRunes["black cobra"] = 3161
monsterWeaknessRunes["black knight"] = 3200
monsterWeaknessRunes["black sheep"] = 3191
monsterWeaknessRunes["black sphinx acolyte"] = 3161
monsterWeaknessRunes["black vixen"] = 3161
monsterWeaknessRunes["blazing fire elemental"] = 3161
monsterWeaknessRunes["blemished spawn"] = 3191
monsterWeaknessRunes["blightwalker"] = 3200
monsterWeaknessRunes["blistering fire elemental"] = 3161
monsterWeaknessRunes["bloated man-maggot"] = 3161
monsterWeaknessRunes["blood beast"] = 3191
monsterWeaknessRunes["blood crab"] = 3191
monsterWeaknessRunes["blood hand"] = 3191
monsterWeaknessRunes["blood priest"] = 3191
monsterWeaknessRunes["bloodback"] = 3191
monsterWeaknessRunes["bloodpaw"] = 3202
monsterWeaknessRunes["blue butterfly"] = 3161
monsterWeaknessRunes["blue djinn"] = 3155
monsterWeaknessRunes["boar"] = 3161
monsterWeaknessRunes["boar man"] = 3161
monsterWeaknessRunes["bog frog"] = 3161
monsterWeaknessRunes["bog raider"] = 3202
monsterWeaknessRunes["bone capsule"] = 3161
monsterWeaknessRunes["bone jaw"] = 3161
monsterWeaknessRunes["bonebeast"] = 3191
monsterWeaknessRunes["bonelord"] = 3191
monsterWeaknessRunes["bones"] = 3161
monsterWeaknessRunes["bonny bunny"] = 3200
monsterWeaknessRunes["bony sea devil"] = 3191
monsterWeaknessRunes["boogey"] = 3202
monsterWeaknessRunes["boogy"] = 3202
monsterWeaknessRunes["bound astral power"] = 3202
monsterWeaknessRunes["bovinus"] = 3161
monsterWeaknessRunes["brachiodemon"] = 3161
monsterWeaknessRunes["bragrumol"] = 3161
monsterWeaknessRunes["brain head"] = 3161
monsterWeaknessRunes["brain parasite"] = 3191
monsterWeaknessRunes["brain squid"] = 3155
monsterWeaknessRunes["braindeath"] = 3191
monsterWeaknessRunes["branchy crawler"] = 3155
monsterWeaknessRunes["breach brood"] = 3175
monsterWeaknessRunes["bretzecutioner"] = 3161
monsterWeaknessRunes["brimstone bug"] = 3161
monsterWeaknessRunes["brinebrute inferniarch"] = 3175
monsterWeaknessRunes["brittle skeleton"] = 3161
monsterWeaknessRunes["broken shaper"] = 3202
monsterWeaknessRunes["brokul"] = 3202
monsterWeaknessRunes["broodrider inferniarch"] = 3161
monsterWeaknessRunes["brother chill"] = 3161
monsterWeaknessRunes["brother freeze"] = 3161
monsterWeaknessRunes["brother worm"] = 3161
monsterWeaknessRunes["brown horse"] = 3161
monsterWeaknessRunes["bruise payne"] = 3202
monsterWeaknessRunes["brutus bloodbeard"] = 3161
monsterWeaknessRunes["bug"] = 3191
monsterWeaknessRunes["bulltaur alchemist"] = 3175
monsterWeaknessRunes["bulltaur brute"] = 3175
monsterWeaknessRunes["bulltaur forgepriest"] = 3161
monsterWeaknessRunes["bullwark"] = 3200
monsterWeaknessRunes["burning book"] = 3161
monsterWeaknessRunes["burning gladiator"] = 3161
monsterWeaknessRunes["burrowing beetle"] = 3161
monsterWeaknessRunes["burster spectre"] = 3191
monsterWeaknessRunes["butterfly"] = 3161
monsterWeaknessRunes["calamary"] = 3202
monsterWeaknessRunes["candy floss elemental"] = 3191
monsterWeaknessRunes["candy horror"] = 3202
monsterWeaknessRunes["canopic jar"] = 3161
monsterWeaknessRunes["capricious phantom"] = 3200
monsterWeaknessRunes["captain jones"] = 3155
monsterWeaknessRunes["captured dwarf"] = 3161
monsterWeaknessRunes["carniphila"] = 3191
monsterWeaknessRunes["carnisylvan sapling"] = 3161
monsterWeaknessRunes["carnivostrich"] = 3161
monsterWeaknessRunes["carrion worm"] = 3161
monsterWeaknessRunes["cart packed with gold"] = 3161
monsterWeaknessRunes["cat"] = 3161
monsterWeaknessRunes["cave chimera"] = 3175
monsterWeaknessRunes["cave devourer"] = 3191
monsterWeaknessRunes["cave parrot"] = 3161
monsterWeaknessRunes["cave rat"] = 3191
monsterWeaknessRunes["cave spider"] = 3191
monsterWeaknessRunes["centipede"] = 3191
monsterWeaknessRunes["cerebellum"] = 3161
monsterWeaknessRunes["chagorz"] = 3161
monsterWeaknessRunes["chakoya toolshaper"] = 3202
monsterWeaknessRunes["chakoya tribewarden"] = 3202
monsterWeaknessRunes["chakoya windcaller"] = 3202
monsterWeaknessRunes["charged disruption"] = 3161
monsterWeaknessRunes["charged energy elemental"] = 3200
monsterWeaknessRunes["charger"] = 3161
monsterWeaknessRunes["charging outburst"] = 3200
monsterWeaknessRunes["chasm spawn"] = 3191
monsterWeaknessRunes["chayenne"] = 3161
monsterWeaknessRunes["cheese thief"] = 3161
monsterWeaknessRunes["chicken"] = 3161
monsterWeaknessRunes["chikhaton"] = 3202
monsterWeaknessRunes["chizzoron the distorter"] = 3191
monsterWeaknessRunes["chocolate blob"] = 3161
monsterWeaknessRunes["choking fear"] = 3202
monsterWeaknessRunes["clay guardian"] = 3191
monsterWeaknessRunes["cliff strider"] = 3202
monsterWeaknessRunes["cloak of terror"] = 3155
monsterWeaknessRunes["clomp"] = 3161
monsterWeaknessRunes["clubarc the plunderer"] = 3200
monsterWeaknessRunes["cobra"] = 3191
monsterWeaknessRunes["cobra assassin"] = 3161
monsterWeaknessRunes["cobra scout"] = 3161
monsterWeaknessRunes["cobra vizier"] = 3161
monsterWeaknessRunes["cockroach"] = 3161
monsterWeaknessRunes["coldheart"] = 3202
monsterWeaknessRunes["colerian the barbarian"] = 3175
monsterWeaknessRunes["concentrated death"] = 3161
monsterWeaknessRunes["condensed sin"] = 3202
monsterWeaknessRunes["condensed sins"] = 3202
monsterWeaknessRunes["containment crystal"] = 3191
monsterWeaknessRunes["containment machine"] = 3155
monsterWeaknessRunes["control tower"] = 3161
monsterWeaknessRunes["converter"] = 3200
monsterWeaknessRunes["coral frog"] = 3191
monsterWeaknessRunes["corrupt naga"] = 3161
monsterWeaknessRunes["corrupted soul"] = 3161
monsterWeaknessRunes["corym charlatan"] = 3161
monsterWeaknessRunes["corym skirmisher"] = 3161
monsterWeaknessRunes["corym vanguard"] = 3191
monsterWeaknessRunes["cosmic energy prism a"] = 3161
monsterWeaknessRunes["cosmic energy prism a invu"] = 3161
monsterWeaknessRunes["cosmic energy prism b"] = 3161
monsterWeaknessRunes["cosmic energy prism b invu"] = 3161
monsterWeaknessRunes["cosmic energy prism c"] = 3161
monsterWeaknessRunes["cosmic energy prism c invu"] = 3161
monsterWeaknessRunes["cosmic energy prism d"] = 3161
monsterWeaknessRunes["cosmic energy prism d invu"] = 3161
monsterWeaknessRunes["count vlarkorth"] = 3155
monsterWeaknessRunes["countess sorrow"] = 3191
monsterWeaknessRunes["courage leech"] = 3155
monsterWeaknessRunes["crab"] = 3202
monsterWeaknessRunes["crape man"] = 3161
monsterWeaknessRunes["crawler"] = 3191
monsterWeaknessRunes["crazed beggar"] = 3175
monsterWeaknessRunes["crazed dwarf"] = 3161
monsterWeaknessRunes["crazed summer rearguard"] = 3161
monsterWeaknessRunes["crazed summer vanguard"] = 3161
monsterWeaknessRunes["crazed winter rearguard"] = 3191
monsterWeaknessRunes["crazed winter vanguard"] = 3191
monsterWeaknessRunes["cream blob"] = 3191
monsterWeaknessRunes["crimson frog"] = 3191
monsterWeaknessRunes["crocodile"] = 3191
monsterWeaknessRunes["crustacea gigantica"] = 3202
monsterWeaknessRunes["crypt defiler"] = 3161
monsterWeaknessRunes["crypt shambler"] = 3161
monsterWeaknessRunes["crypt warden"] = 3155
monsterWeaknessRunes["crypt warrior"] = 3202
monsterWeaknessRunes["crystal spider"] = 3202
monsterWeaknessRunes["crystal wolf"] = 3202
monsterWeaknessRunes["crystalcrusher"] = 3202
monsterWeaknessRunes["cult believer"] = 3155
monsterWeaknessRunes["cult enforcer"] = 3161
monsterWeaknessRunes["cult scholar"] = 3200
monsterWeaknessRunes["cunning werepanther"] = 3175
monsterWeaknessRunes["cursed ape"] = 3161
monsterWeaknessRunes["cursed book"] = 3202
monsterWeaknessRunes["cursed gladiator"] = 3191
monsterWeaknessRunes["cursed prospector"] = 3161
monsterWeaknessRunes["custodian"] = 3161
monsterWeaknessRunes["cyclops"] = 3175
monsterWeaknessRunes["cyclops drone"] = 3175
monsterWeaknessRunes["cyclops smith"] = 3175
monsterWeaknessRunes["damage resonance"] = 3161
monsterWeaknessRunes["damaged crystal golem"] = 3202
monsterWeaknessRunes["damaged worker golem"] = 3202
monsterWeaknessRunes["damned soul"] = 3202
monsterWeaknessRunes["darakan the executioner"] = 3191
monsterWeaknessRunes["dark apprentice"] = 3155
monsterWeaknessRunes["dark carnisylvan"] = 3191
monsterWeaknessRunes["dark druid"] = 3161
monsterWeaknessRunes["dark faun"] = 3202
monsterWeaknessRunes["dark knight"] = 3161
monsterWeaknessRunes["dark knowledge"] = 3161
monsterWeaknessRunes["dark magician"] = 3155
monsterWeaknessRunes["dark monk"] = 3200
monsterWeaknessRunes["dark paladin"] = 3161
monsterWeaknessRunes["dark sorcerer"] = 3161
monsterWeaknessRunes["dark soul"] = 3161
monsterWeaknessRunes["dark torturer"] = 3161
monsterWeaknessRunes["darkfang"] = 3191
monsterWeaknessRunes["darklight construct"] = 3155
monsterWeaknessRunes["darklight emitter"] = 3155
monsterWeaknessRunes["darklight matter"] = 3191
monsterWeaknessRunes["darklight source"] = 3191
monsterWeaknessRunes["darklight striker"] = 3191
monsterWeaknessRunes["dawn bat"] = 3175
monsterWeaknessRunes["dawn scorpion"] = 3161
monsterWeaknessRunes["dawnfire asura"] = 3161
monsterWeaknessRunes["dawnfly"] = 3191
monsterWeaknessRunes["dazed leaf golem"] = 3161
monsterWeaknessRunes["deadeye devious"] = 3161
monsterWeaknessRunes["death blob"] = 3202
monsterWeaknessRunes["death dragon"] = 3202
monsterWeaknessRunes["death priest"] = 3161
monsterWeaknessRunes["death priest shargon"] = 3161
monsterWeaknessRunes["deathbine"] = 3191
monsterWeaknessRunes["deathbringer"] = 3202
monsterWeaknessRunes["deathling scout"] = 3202
monsterWeaknessRunes["deathling spellsinger"] = 3202
monsterWeaknessRunes["deathspawn"] = 3200
monsterWeaknessRunes["deathstrike"] = 3200
monsterWeaknessRunes["deep terror"] = 3161
monsterWeaknessRunes["deepling brawler"] = 3202
monsterWeaknessRunes["deepling elite"] = 3202
monsterWeaknessRunes["deepling guard"] = 3202
monsterWeaknessRunes["deepling master librarian"] = 3202
monsterWeaknessRunes["deepling scout"] = 3202
monsterWeaknessRunes["deepling spellsinger"] = 3202
monsterWeaknessRunes["deepling tyrant"] = 3202
monsterWeaknessRunes["deepling warrior"] = 3202
monsterWeaknessRunes["deepling worker"] = 3202
monsterWeaknessRunes["deepsea blood crab"] = 3191
monsterWeaknessRunes["deepworm"] = 3191
monsterWeaknessRunes["deer"] = 3161
monsterWeaknessRunes["defiler"] = 3191
monsterWeaknessRunes["demodras"] = 3161
monsterWeaknessRunes["demon"] = 3161
monsterWeaknessRunes["demon blood"] = 3161
monsterWeaknessRunes["demon goblin"] = 3175
monsterWeaknessRunes["demon outcast"] = 3202
monsterWeaknessRunes["demon parrot"] = 3161
monsterWeaknessRunes["demon skeleton"] = 3161
monsterWeaknessRunes["demon slave"] = 3161
monsterWeaknessRunes["depolarized crackler"] = 3175
monsterWeaknessRunes["depowered minotaur"] = 3161
monsterWeaknessRunes["despair"] = 3161
monsterWeaknessRunes["desperate white deer"] = 3161
monsterWeaknessRunes["destabilized ferumbras"] = 3161
monsterWeaknessRunes["destroyed pillar"] = 3161
monsterWeaknessRunes["destroyer"] = 3161
monsterWeaknessRunes["devourer"] = 3202
monsterWeaknessRunes["dharalion"] = 3161
monsterWeaknessRunes["diabolic imp"] = 3161
monsterWeaknessRunes["diamond servant"] = 3161
monsterWeaknessRunes["diamond servant replica"] = 3161
monsterWeaknessRunes["diblis the fair"] = 3161
monsterWeaknessRunes["dipthrah"] = 3202
monsterWeaknessRunes["dire penguin"] = 3202
monsterWeaknessRunes["diremaw"] = 3161
monsterWeaknessRunes["dirtbeard"] = 3191
monsterWeaknessRunes["diseased bill"] = 3200
monsterWeaknessRunes["diseased dan"] = 3202
monsterWeaknessRunes["diseased fred"] = 3161
monsterWeaknessRunes["disgusting ooze"] = 3202
monsterWeaknessRunes["disruption"] = 3161
monsterWeaknessRunes["distorted phantom"] = 3200
monsterWeaknessRunes["doctor marrow"] = 3161
monsterWeaknessRunes["doctor perhaps"] = 3200
monsterWeaknessRunes["dog"] = 3161
monsterWeaknessRunes["donkey"] = 3161
monsterWeaknessRunes["doom deer"] = 3161
monsterWeaknessRunes["doomhowl"] = 3161
monsterWeaknessRunes["dorokoll the mystic"] = 3161
monsterWeaknessRunes["dracola"] = 3202
monsterWeaknessRunes["dragolisk"] = 3175
monsterWeaknessRunes["dragon"] = 3161
monsterWeaknessRunes["dragon egg"] = 3161
monsterWeaknessRunes["dragon essence"] = 3202
monsterWeaknessRunes["dragon hatchling"] = 3161
monsterWeaknessRunes["dragon hoard"] = 3161
monsterWeaknessRunes["dragon lord"] = 3161
monsterWeaknessRunes["dragon lord hatchling"] = 3161
monsterWeaknessRunes["dragon servant"] = 3161
monsterWeaknessRunes["dragon warden"] = 3161
monsterWeaknessRunes["dragon wrath"] = 3202
monsterWeaknessRunes["dragonling"] = 3175
monsterWeaknessRunes["draken abomination"] = 3202
monsterWeaknessRunes["draken elite"] = 3161
monsterWeaknessRunes["draken spellweaver"] = 3161
monsterWeaknessRunes["draken warmaster"] = 3161
monsterWeaknessRunes["draptor"] = 3175
monsterWeaknessRunes["drasilla"] = 3161
monsterWeaknessRunes["dread intruder"] = 3175
monsterWeaknessRunes["dread minion"] = 3161
monsterWeaknessRunes["dreadbeast"] = 3202
monsterWeaknessRunes["dreadful disruptor"] = 3175
monsterWeaknessRunes["dreadful harvester"] = 3161
monsterWeaknessRunes["dreadmaw"] = 3202
monsterWeaknessRunes["dreadwing"] = 3161
monsterWeaknessRunes["drillworm"] = 3191
monsterWeaknessRunes["dromedary"] = 3161
monsterWeaknessRunes["druid familiar"] = 3161
monsterWeaknessRunes["druid's apparition"] = 3191
monsterWeaknessRunes["drume"] = 3202
monsterWeaknessRunes["dryad"] = 3191
monsterWeaknessRunes["duke krule"] = 3191
monsterWeaknessRunes["duskbringer"] = 3161
monsterWeaknessRunes["dwarf"] = 3191
monsterWeaknessRunes["dwarf geomancer"] = 3155
monsterWeaknessRunes["dwarf guard"] = 3191
monsterWeaknessRunes["dwarf henchman"] = 3161
monsterWeaknessRunes["dwarf miner"] = 3161
monsterWeaknessRunes["dwarf soldier"] = 3191
monsterWeaknessRunes["dworc fleshhunter"] = 3155
monsterWeaknessRunes["dworc venomsniper"] = 3161
monsterWeaknessRunes["dworc voodoomaster"] = 3191
monsterWeaknessRunes["earl osam"] = 3191
monsterWeaknessRunes["earth elemental"] = 3191
monsterWeaknessRunes["earth overlord"] = 3191
monsterWeaknessRunes["earworm"] = 3161
monsterWeaknessRunes["echo of chagorz"] = 3161
monsterWeaknessRunes["echo of ichgahal"] = 3161
monsterWeaknessRunes["echo of murcion"] = 3161
monsterWeaknessRunes["echo of vemiath"] = 3161
monsterWeaknessRunes["eclipse knight"] = 3161
monsterWeaknessRunes["efreet"] = 3161
monsterWeaknessRunes["egg"] = 3161
monsterWeaknessRunes["ekatrix"] = 3161
monsterWeaknessRunes["elder bloodjaw"] = 3155
monsterWeaknessRunes["elder bonelord"] = 3191
monsterWeaknessRunes["elder mummy"] = 3202
monsterWeaknessRunes["elder wyrm"] = 3161
monsterWeaknessRunes["elephant"] = 3202
monsterWeaknessRunes["elf"] = 3155
monsterWeaknessRunes["elf arcanist"] = 3161
monsterWeaknessRunes["elf overseer"] = 3161
monsterWeaknessRunes["elf scout"] = 3155
monsterWeaknessRunes["elite pirat"] = 3161
monsterWeaknessRunes["eliz the unyielding"] = 3161
monsterWeaknessRunes["elvira hammerthrust"] = 3191
monsterWeaknessRunes["ember beast"] = 3161
monsterWeaknessRunes["emerald damselfly"] = 3161
monsterWeaknessRunes["emerald tortoise"] = 3155
monsterWeaknessRunes["empowered glooth horror"] = 3161
monsterWeaknessRunes["energetic book"] = 3175
monsterWeaknessRunes["energized raging mage"] = 3200
monsterWeaknessRunes["energuardian of tales"] = 3175
monsterWeaknessRunes["energy elemental"] = 3175
monsterWeaknessRunes["energy overlord"] = 3175
monsterWeaknessRunes["energy pulse"] = 3161
monsterWeaknessRunes["enfeebled silencer"] = 3200
monsterWeaknessRunes["enlightened of the cult"] = 3202
monsterWeaknessRunes["enpa yolo"] = 3161
monsterWeaknessRunes["enraged crystal golem"] = 3202
monsterWeaknessRunes["enraged sand brood"] = 3161
monsterWeaknessRunes["enraged soul"] = 3161
monsterWeaknessRunes["enraged squirrel"] = 3161
monsterWeaknessRunes["enraged white deer"] = 3161
monsterWeaknessRunes["enslaved dwarf"] = 3200
monsterWeaknessRunes["enthralled demon"] = 3161
monsterWeaknessRunes["eradicator"] = 3155
monsterWeaknessRunes["eradicator2"] = 3155
monsterWeaknessRunes["eruption of destruction"] = 3161
monsterWeaknessRunes["eshtaba the conjurer"] = 3161
monsterWeaknessRunes["esmeralda"] = 3191
monsterWeaknessRunes["essence of darkness"] = 3191
monsterWeaknessRunes["essence of malice"] = 3202
monsterWeaknessRunes["eternal guardian"] = 3161
monsterWeaknessRunes["ethershreck"] = 3202
monsterWeaknessRunes["evil mastermind"] = 3191
monsterWeaknessRunes["evil prospector"] = 3155
monsterWeaknessRunes["evil sheep"] = 3191
monsterWeaknessRunes["evil sheep lord"] = 3191
monsterWeaknessRunes["execowtioner"] = 3191
monsterWeaknessRunes["exotic bat"] = 3191
monsterWeaknessRunes["exotic cave spider"] = 3191
monsterWeaknessRunes["eyeless devourer"] = 3200
monsterWeaknessRunes["faceless bane"] = 3191
monsterWeaknessRunes["fahim the wise"] = 3161
monsterWeaknessRunes["falcon knight"] = 3161
monsterWeaknessRunes["falcon paladin"] = 3161
monsterWeaknessRunes["fallen challenger"] = 3202
monsterWeaknessRunes["fallen mooh'tah master ghar"] = 3161
monsterWeaknessRunes["fatality"] = 3191
monsterWeaknessRunes["faun"] = 3191
monsterWeaknessRunes["fazzrah"] = 3175
monsterWeaknessRunes["feeble glooth horror"] = 3191
monsterWeaknessRunes["feral sphinx"] = 3161
monsterWeaknessRunes["feral werecrocodile"] = 3161
monsterWeaknessRunes["fernfang"] = 3202
monsterWeaknessRunes["feroxa"] = 3161
monsterWeaknessRunes["feroxa3"] = 3161
monsterWeaknessRunes["feroxa4"] = 3161
monsterWeaknessRunes["feroxa5"] = 3161
monsterWeaknessRunes["ferumbras"] = 3155
monsterWeaknessRunes["ferumbras essence"] = 3161
monsterWeaknessRunes["ferumbras mortal shell"] = 3200
monsterWeaknessRunes["ferumbras soul splinter"] = 3191
monsterWeaknessRunes["fetter"] = 3202
monsterWeaknessRunes["feverish citizen"] = 3191
monsterWeaknessRunes["feversleep"] = 3202
monsterWeaknessRunes["fiery blood"] = 3161
monsterWeaknessRunes["fiery heart"] = 3161
monsterWeaknessRunes["filth toad"] = 3191
monsterWeaknessRunes["fire devil"] = 3161
monsterWeaknessRunes["fire elemental"] = 3161
monsterWeaknessRunes["fire overlord"] = 3161
monsterWeaknessRunes["firestarter"] = 3161
monsterWeaknessRunes["fish"] = 3202
monsterWeaknessRunes["flame of omrafir"] = 3161
monsterWeaknessRunes["flameborn"] = 3161
monsterWeaknessRunes["flamingo"] = 3161
monsterWeaknessRunes["fleabringer"] = 3161
monsterWeaknessRunes["fleshcrawler"] = 3191
monsterWeaknessRunes["fleshslicer"] = 3161
monsterWeaknessRunes["flickering spirit elemental"] = 3191
monsterWeaknessRunes["flimsy lost soul"] = 3161
monsterWeaknessRunes["floating savant"] = 3161
monsterWeaknessRunes["fluffy"] = 3161
monsterWeaknessRunes["flying book"] = 3202
monsterWeaknessRunes["foam stalker"] = 3202
monsterWeaknessRunes["force field"] = 3200
monsterWeaknessRunes["foreman kneebiter"] = 3191
monsterWeaknessRunes["foreshock"] = 3161
monsterWeaknessRunes["forest fury"] = 3191
monsterWeaknessRunes["fox"] = 3191
monsterWeaknessRunes["frazzlemaw"] = 3161
monsterWeaknessRunes["freakish lost soul"] = 3161
monsterWeaknessRunes["freed soul"] = 3161
monsterWeaknessRunes["freegoiz"] = 3161
monsterWeaknessRunes["frenzy"] = 3161
monsterWeaknessRunes["frost dragon"] = 3202
monsterWeaknessRunes["frost dragon hatchling"] = 3202
monsterWeaknessRunes["frost flower asura"] = 3191
monsterWeaknessRunes["frost giant"] = 3202
monsterWeaknessRunes["frost giantess"] = 3202
monsterWeaknessRunes["frost servant"] = 3161
monsterWeaknessRunes["frost troll"] = 3202
monsterWeaknessRunes["frostfur"] = 3202
monsterWeaknessRunes["frozen minion"] = 3161
monsterWeaknessRunes["fruit drop"] = 3191
monsterWeaknessRunes["fungosaurus"] = 3161
monsterWeaknessRunes["furious scorpion"] = 3161
monsterWeaknessRunes["furious troll"] = 3161
monsterWeaknessRunes["fury"] = 3202
monsterWeaknessRunes["fury of the emperor"] = 3202
monsterWeaknessRunes["furyosa"] = 3175
monsterWeaknessRunes["gaffir"] = 3161
monsterWeaknessRunes["gang member"] = 3155
monsterWeaknessRunes["gargoyle"] = 3191
monsterWeaknessRunes["gaz'haragoth"] = 3161
monsterWeaknessRunes["gazer"] = 3191
monsterWeaknessRunes["gazer spectre"] = 3161
monsterWeaknessRunes["gelidrazah the frozen"] = 3191
monsterWeaknessRunes["general murius"] = 3161
monsterWeaknessRunes["generator"] = 3155
monsterWeaknessRunes["ghastly dragon"] = 3202
monsterWeaknessRunes["ghazbaran"] = 3202
monsterWeaknessRunes["ghost"] = 3161
monsterWeaknessRunes["ghost wolf"] = 3191
monsterWeaknessRunes["ghoul"] = 3191
monsterWeaknessRunes["ghoulish hyaena"] = 3191
monsterWeaknessRunes["ghulosh"] = 3175
monsterWeaknessRunes["giant spider"] = 3191
monsterWeaknessRunes["giant spider wyda"] = 3191
monsterWeaknessRunes["gingerbread man"] = 3191
monsterWeaknessRunes["girtablilu warrior"] = 3202
monsterWeaknessRunes["gladiator"] = 3155
monsterWeaknessRunes["glitterscale"] = 3161
monsterWeaknessRunes["gloom wolf"] = 3161
monsterWeaknessRunes["glooth anemone"] = 3191
monsterWeaknessRunes["glooth bandit"] = 3191
monsterWeaknessRunes["glooth battery"] = 3155
monsterWeaknessRunes["glooth blob"] = 3202
monsterWeaknessRunes["glooth bomb"] = 3161
monsterWeaknessRunes["glooth brigand"] = 3191
monsterWeaknessRunes["glooth fairy"] = 3191
monsterWeaknessRunes["glooth golem"] = 3191
monsterWeaknessRunes["glooth horror"] = 3191
monsterWeaknessRunes["glooth masher"] = 3161
monsterWeaknessRunes["glooth powered minotaur"] = 3161
monsterWeaknessRunes["glooth slasher"] = 3161
monsterWeaknessRunes["glooth trasher"] = 3161
monsterWeaknessRunes["glooth-generator"] = 3161
monsterWeaknessRunes["gnarlhound"] = 3161
monsterWeaknessRunes["gnome pack crawler"] = 3161
monsterWeaknessRunes["gnomevil"] = 3200
monsterWeaknessRunes["gnorre chyllson"] = 3202
monsterWeaknessRunes["goblin"] = 3175
monsterWeaknessRunes["goblin assassin"] = 3175
monsterWeaknessRunes["goblin leader"] = 3161
monsterWeaknessRunes["goblin scavenger"] = 3175
monsterWeaknessRunes["goggle cake"] = 3161
monsterWeaknessRunes["golden servant"] = 3161
monsterWeaknessRunes["golden servant replica"] = 3161
monsterWeaknessRunes["goldhanded cultist"] = 3175
monsterWeaknessRunes["golgordan"] = 3161
monsterWeaknessRunes["gore horn"] = 3161
monsterWeaknessRunes["gorerilla"] = 3161
monsterWeaknessRunes["gorger inferniarch"] = 3161
monsterWeaknessRunes["gorgo"] = 3202
monsterWeaknessRunes["gorzindel"] = 3161
monsterWeaknessRunes["goshnar's cruelty"] = 3161
monsterWeaknessRunes["goshnar's greed"] = 3161
monsterWeaknessRunes["goshnar's hatred"] = 3161
monsterWeaknessRunes["goshnar's malice"] = 3161
monsterWeaknessRunes["goshnar's megalomania blue"] = 3161
monsterWeaknessRunes["goshnar's megalomania green"] = 3161
monsterWeaknessRunes["goshnar's spite"] = 3161
monsterWeaknessRunes["gozzler"] = 3200
monsterWeaknessRunes["grand canon dominus"] = 3161
monsterWeaknessRunes["grand chaplain gaunder"] = 3161
monsterWeaknessRunes["grand commander soeren"] = 3161
monsterWeaknessRunes["grand master oberon"] = 3161
monsterWeaknessRunes["grand mother foulscale"] = 3161
monsterWeaknessRunes["grandfather tridian"] = 3161
monsterWeaknessRunes["grave guard"] = 3161
monsterWeaknessRunes["grave robber"] = 3161
monsterWeaknessRunes["gravedigger"] = 3191
monsterWeaknessRunes["gravelord oshuran"] = 3200
monsterWeaknessRunes["greater canopic jar"] = 3161
monsterWeaknessRunes["greater death minion"] = 3161
monsterWeaknessRunes["greedbeast"] = 3191
monsterWeaknessRunes["green djinn"] = 3161
monsterWeaknessRunes["green frog"] = 3161
monsterWeaknessRunes["grey horse"] = 3161
monsterWeaknessRunes["grim reaper"] = 3202
monsterWeaknessRunes["grimeleech"] = 3202
monsterWeaknessRunes["grimgor guteater"] = 3175
monsterWeaknessRunes["groam"] = 3202
monsterWeaknessRunes["grorlam"] = 3191
monsterWeaknessRunes["grynch clan goblin"] = 3161
monsterWeaknessRunes["gryphon"] = 3161
monsterWeaknessRunes["guard captain quaid"] = 3161
monsterWeaknessRunes["guardian of tales"] = 3161
monsterWeaknessRunes["guzzlemaw"] = 3161
monsterWeaknessRunes["hacker"] = 3161
monsterWeaknessRunes["hairman the huge"] = 3161
monsterWeaknessRunes["hand of cursed fate"] = 3161
monsterWeaknessRunes["hardened usurper archer"] = 3161
monsterWeaknessRunes["hardened usurper knight"] = 3161
monsterWeaknessRunes["hardened usurper warlock"] = 3161
monsterWeaknessRunes["harpy"] = 3161
monsterWeaknessRunes["hateful soul"] = 3161
monsterWeaknessRunes["haunted dragon"] = 3202
monsterWeaknessRunes["haunted treeling"] = 3191
monsterWeaknessRunes["haunter"] = 3161
monsterWeaknessRunes["hazardous phantom"] = 3161
monsterWeaknessRunes["headpecker"] = 3161
monsterWeaknessRunes["hellfire fighter"] = 3161
monsterWeaknessRunes["hellflayer"] = 3202
monsterWeaknessRunes["hellgorak"] = 3161
monsterWeaknessRunes["hellhound"] = 3161
monsterWeaknessRunes["hellhunter inferniarch"] = 3175
monsterWeaknessRunes["hellspawn"] = 3161
monsterWeaknessRunes["hemming"] = 3161
monsterWeaknessRunes["heoni"] = 3191
monsterWeaknessRunes["herald of gloom"] = 3200
monsterWeaknessRunes["hero"] = 3155
monsterWeaknessRunes["hibernal moth"] = 3191
monsterWeaknessRunes["hide"] = 3161
monsterWeaknessRunes["hideous fungus"] = 3191
monsterWeaknessRunes["high voltage elemental"] = 3191
monsterWeaknessRunes["hirintror"] = 3202
monsterWeaknessRunes["hive overseer"] = 3161
monsterWeaknessRunes["honey elemental"] = 3202
monsterWeaknessRunes["honour guard"] = 3161
monsterWeaknessRunes["horadron"] = 3155
monsterWeaknessRunes["horestis"] = 3200
monsterWeaknessRunes["horrible dream"] = 3161
monsterWeaknessRunes["horse"] = 3161
monsterWeaknessRunes["hot dog"] = 3161
monsterWeaknessRunes["hulking carnisylvan"] = 3191
monsterWeaknessRunes["hulking prehemoth"] = 3161
monsterWeaknessRunes["humongous fungus"] = 3191
monsterWeaknessRunes["humorless fungus"] = 3155
monsterWeaknessRunes["hunter"] = 3200
monsterWeaknessRunes["husky"] = 3161
monsterWeaknessRunes["hyaena"] = 3161
monsterWeaknessRunes["hydra"] = 3202
monsterWeaknessRunes["ice dragon"] = 3191
monsterWeaknessRunes["ice golem"] = 3202
monsterWeaknessRunes["ice overlord"] = 3202
monsterWeaknessRunes["ice witch"] = 3202
monsterWeaknessRunes["icecold book"] = 3191
monsterWeaknessRunes["ichgahal"] = 3161
monsterWeaknessRunes["iks ahpututu"] = 3200
monsterWeaknessRunes["iks aucar"] = 3155
monsterWeaknessRunes["iks chuka"] = 3202
monsterWeaknessRunes["iks churrascan"] = 3155
monsterWeaknessRunes["iks pututu"] = 3200
monsterWeaknessRunes["iks yapunac"] = 3155
monsterWeaknessRunes["imp intruder"] = 3161
monsterWeaknessRunes["incineron"] = 3175
monsterWeaknessRunes["infected weeper"] = 3191
monsterWeaknessRunes["infernal demon"] = 3161
monsterWeaknessRunes["infernal frog"] = 3161
monsterWeaknessRunes["infernal phantom"] = 3161
monsterWeaknessRunes["infernalist"] = 3161
monsterWeaknessRunes["infernatil"] = 3161
monsterWeaknessRunes["ink blob"] = 3202
monsterWeaknessRunes["inky"] = 3202
monsterWeaknessRunes["insane siren"] = 3161
monsterWeaknessRunes["insect swarm"] = 3191
monsterWeaknessRunes["insectoid scout"] = 3161
monsterWeaknessRunes["insectoid worker"] = 3161
monsterWeaknessRunes["instable breach brood"] = 3175
monsterWeaknessRunes["instable sparkion"] = 3175
monsterWeaknessRunes["invading demon"] = 3161
monsterWeaknessRunes["irgix the flimsy"] = 3161
monsterWeaknessRunes["iron servant"] = 3175
monsterWeaknessRunes["iron servant replica"] = 3175
monsterWeaknessRunes["ironblight"] = 3200
monsterWeaknessRunes["island troll"] = 3161
monsterWeaknessRunes["izcandar champion of summer"] = 3161
monsterWeaknessRunes["izcandar champion of winter"] = 3161
monsterWeaknessRunes["izcandar the banished"] = 3161
monsterWeaknessRunes["jagged earth elemental"] = 3191
monsterWeaknessRunes["jailer"] = 3161
monsterWeaknessRunes["jaul"] = 3200
monsterWeaknessRunes["jellyfish"] = 3202
monsterWeaknessRunes["jesse the wicked"] = 3161
monsterWeaknessRunes["juggernaut"] = 3202
monsterWeaknessRunes["jungle moa"] = 3155
monsterWeaknessRunes["juvenile bashmu"] = 3161
monsterWeaknessRunes["juvenile cyclops"] = 3161
monsterWeaknessRunes["kalyassa"] = 3161
monsterWeaknessRunes["katex blood tongue"] = 3161
monsterWeaknessRunes["kerberos"] = 3161
monsterWeaknessRunes["kesar"] = 3161
monsterWeaknessRunes["killer caiman"] = 3202
monsterWeaknessRunes["killer rabbit"] = 3161
monsterWeaknessRunes["king zelos"] = 3161
monsterWeaknessRunes["knight familiar"] = 3161
monsterWeaknessRunes["knight's apparition"] = 3191
monsterWeaknessRunes["knowledge elemental"] = 3155
monsterWeaknessRunes["knowledge raider"] = 3161
monsterWeaknessRunes["kollos"] = 3161
monsterWeaknessRunes["kongra"] = 3161
monsterWeaknessRunes["koshei the deathless"] = 3191
monsterWeaknessRunes["kraknaknork"] = 3161
monsterWeaknessRunes["kreebosh the exile"] = 3155
monsterWeaknessRunes["kroazur"] = 3155
monsterWeaknessRunes["lacewing moth"] = 3202
monsterWeaknessRunes["lady tenebris"] = 3200
monsterWeaknessRunes["ladybug"] = 3191
monsterWeaknessRunes["lamassu"] = 3155
monsterWeaknessRunes["lancer beetle"] = 3161
monsterWeaknessRunes["larva"] = 3191
monsterWeaknessRunes["last planegazer"] = 3200
monsterWeaknessRunes["latrivan"] = 3161
monsterWeaknessRunes["lava creature"] = 3161
monsterWeaknessRunes["lava golem"] = 3161
monsterWeaknessRunes["lava lurker"] = 3161
monsterWeaknessRunes["lava lurker attendant"] = 3161
monsterWeaknessRunes["lavafungus"] = 3161
monsterWeaknessRunes["lavaworm"] = 3161
monsterWeaknessRunes["leaf golem"] = 3161
monsterWeaknessRunes["leiden"] = 3161
monsterWeaknessRunes["lesser death minion"] = 3161
monsterWeaknessRunes["lesser fire devil"] = 3161
monsterWeaknessRunes["lesser swarmer"] = 3161
monsterWeaknessRunes["lethal lissy"] = 3161
monsterWeaknessRunes["leviathan"] = 3200
monsterWeaknessRunes["lich"] = 3161
monsterWeaknessRunes["liodile"] = 3161
monsterWeaknessRunes["lion"] = 3161
monsterWeaknessRunes["lion archer"] = 3161
monsterWeaknessRunes["lion commander"] = 3161
monsterWeaknessRunes["lion knight"] = 3161
monsterWeaknessRunes["lion warlock"] = 3161
monsterWeaknessRunes["liquor spirit"] = 3161
monsterWeaknessRunes["lisa"] = 3191
monsterWeaknessRunes["little corym charlatan"] = 3161
monsterWeaknessRunes["lizard abomination"] = 3202
monsterWeaknessRunes["lizard chosen"] = 3155
monsterWeaknessRunes["lizard dragon priest"] = 3161
monsterWeaknessRunes["lizard high guard"] = 3161
monsterWeaknessRunes["lizard legionnaire"] = 3161
monsterWeaknessRunes["lizard magistratus"] = 3161
monsterWeaknessRunes["lizard noble"] = 3161
monsterWeaknessRunes["lizard sentinel"] = 3191
monsterWeaknessRunes["lizard snakecharmer"] = 3191
monsterWeaknessRunes["lizard templar"] = 3191
monsterWeaknessRunes["lizard zaogun"] = 3200
monsterWeaknessRunes["lloyd"] = 3161
monsterWeaknessRunes["lokathmor"] = 3175
monsterWeaknessRunes["lord azaram"] = 3191
monsterWeaknessRunes["lord of the elements"] = 3161
monsterWeaknessRunes["lost basher"] = 3161
monsterWeaknessRunes["lost berserker"] = 3161
monsterWeaknessRunes["lost exile"] = 3200
monsterWeaknessRunes["lost gnome"] = 3161
monsterWeaknessRunes["lost husher"] = 3161
monsterWeaknessRunes["lost soul"] = 3200
monsterWeaknessRunes["lost thrower"] = 3161
monsterWeaknessRunes["lost time"] = 3161
monsterWeaknessRunes["lovely deer"] = 3155
monsterWeaknessRunes["lovely frazzlemaw"] = 3155
monsterWeaknessRunes["lovely polar bear"] = 3155
monsterWeaknessRunes["lovely rotworm"] = 3155
monsterWeaknessRunes["lovely scorpion"] = 3155
monsterWeaknessRunes["lovely snake"] = 3155
monsterWeaknessRunes["lovely souleater"] = 3155
monsterWeaknessRunes["lovely yielothax"] = 3155
monsterWeaknessRunes["lucifuga aranea"] = 3161
monsterWeaknessRunes["lumbering carnivor"] = 3191
monsterWeaknessRunes["mad mage"] = 3200
monsterWeaknessRunes["mad scientist"] = 3155
monsterWeaknessRunes["mad technomancer"] = 3202
monsterWeaknessRunes["madareth"] = 3191
monsterWeaknessRunes["magical sphere"] = 3155
monsterWeaknessRunes["magma bubble"] = 3161
monsterWeaknessRunes["magma crawler"] = 3161
monsterWeaknessRunes["magma crystal"] = 3161
monsterWeaknessRunes["magnor mournbringer"] = 3191
monsterWeaknessRunes["mahrdis"] = 3161
monsterWeaknessRunes["makara"] = 3202
monsterWeaknessRunes["makeshift home"] = 3191
monsterWeaknessRunes["malicious minion"] = 3161
monsterWeaknessRunes["malicious soul"] = 3161
monsterWeaknessRunes["malkhar deathbringer"] = 3161
monsterWeaknessRunes["malofur mangrinder"] = 3161
monsterWeaknessRunes["mammoth"] = 3191
monsterWeaknessRunes["man in the cave"] = 3161
monsterWeaknessRunes["manta ray"] = 3202
monsterWeaknessRunes["manticore"] = 3161
monsterWeaknessRunes["mantosaurus"] = 3161
monsterWeaknessRunes["many faces"] = 3155
monsterWeaknessRunes["marid"] = 3155
monsterWeaknessRunes["marsh stalker"] = 3175
monsterWeaknessRunes["massacre"] = 3155
monsterWeaknessRunes["massive earth elemental"] = 3191
monsterWeaknessRunes["massive energy elemental"] = 3175
monsterWeaknessRunes["massive fire elemental"] = 3161
monsterWeaknessRunes["massive water elemental"] = 3202
monsterWeaknessRunes["mawhawk"] = 3202
monsterWeaknessRunes["maxxenius"] = 3191
monsterWeaknessRunes["mazoran"] = 3161
monsterWeaknessRunes["mazzinor"] = 3161
monsterWeaknessRunes["meadow strider"] = 3161
monsterWeaknessRunes["mean lost soul"] = 3161
monsterWeaknessRunes["mean maw"] = 3161
monsterWeaknessRunes["mean minion"] = 3161
monsterWeaknessRunes["meandering mushroom"] = 3175
monsterWeaknessRunes["mechanical fighter"] = 3161
monsterWeaknessRunes["medusa"] = 3202
monsterWeaknessRunes["mega dragon"] = 3202
monsterWeaknessRunes["megasylvan yselda"] = 3191
monsterWeaknessRunes["melting frozen horror"] = 3191
monsterWeaknessRunes["memory of a banshee"] = 3161
monsterWeaknessRunes["memory of a book"] = 3161
monsterWeaknessRunes["memory of a carnisylvan"] = 3161
monsterWeaknessRunes["memory of a dwarf"] = 3161
monsterWeaknessRunes["memory of a faun"] = 3161
monsterWeaknessRunes["memory of a frazzlemaw"] = 3161
monsterWeaknessRunes["memory of a fungus"] = 3161
monsterWeaknessRunes["memory of a golem"] = 3161
monsterWeaknessRunes["memory of a hero"] = 3161
monsterWeaknessRunes["memory of a hydra"] = 3161
monsterWeaknessRunes["memory of a lizard"] = 3161
monsterWeaknessRunes["memory of a mammoth"] = 3161
monsterWeaknessRunes["memory of a manticore"] = 3161
monsterWeaknessRunes["memory of a pirate"] = 3161
monsterWeaknessRunes["memory of a scarab"] = 3161
monsterWeaknessRunes["memory of a shaper"] = 3161
monsterWeaknessRunes["memory of a vampire"] = 3161
monsterWeaknessRunes["memory of a werelion"] = 3161
monsterWeaknessRunes["memory of a wolf"] = 3161
monsterWeaknessRunes["memory of a yalahari"] = 3161
monsterWeaknessRunes["memory of an amazon"] = 3161
monsterWeaknessRunes["memory of an elf"] = 3161
monsterWeaknessRunes["memory of an insectoid"] = 3161
monsterWeaknessRunes["memory of an ogre"] = 3161
monsterWeaknessRunes["menace"] = 3191
monsterWeaknessRunes["menacing carnivor"] = 3161
monsterWeaknessRunes["mephiles"] = 3161
monsterWeaknessRunes["mercurial menace"] = 3202
monsterWeaknessRunes["mercury blob"] = 3202
monsterWeaknessRunes["merikh the slaughterer"] = 3161
monsterWeaknessRunes["merlkin"] = 3161
monsterWeaknessRunes["metal gargoyle"] = 3202
monsterWeaknessRunes["mezlon the defiler"] = 3161
monsterWeaknessRunes["midnight asura"] = 3202
monsterWeaknessRunes["midnight panther"] = 3155
monsterWeaknessRunes["midnight spawn"] = 3161
monsterWeaknessRunes["mind-wrecking dream"] = 3161
monsterWeaknessRunes["minion of gaz'haragoth"] = 3191
monsterWeaknessRunes["minion of versperoth"] = 3161
monsterWeaknessRunes["minishabaal"] = 3161
monsterWeaknessRunes["minotaur"] = 3161
monsterWeaknessRunes["minotaur amazon"] = 3202
monsterWeaknessRunes["minotaur archer"] = 3161
monsterWeaknessRunes["minotaur bruiser"] = 3161
monsterWeaknessRunes["minotaur cult follower"] = 3161
monsterWeaknessRunes["minotaur cult prophet"] = 3161
monsterWeaknessRunes["minotaur cult zealot"] = 3161
monsterWeaknessRunes["minotaur guard"] = 3161
monsterWeaknessRunes["minotaur hunter"] = 3161
monsterWeaknessRunes["minotaur idol"] = 3161
monsterWeaknessRunes["minotaur invader"] = 3161
monsterWeaknessRunes["minotaur mage"] = 3161
monsterWeaknessRunes["minotaur occultist"] = 3161
monsterWeaknessRunes["minotaur poacher"] = 3161
monsterWeaknessRunes["minotaur totem"] = 3155
monsterWeaknessRunes["mirror image"] = 3191
monsterWeaknessRunes["misguided bully"] = 3202
monsterWeaknessRunes["misguided shadow"] = 3161
monsterWeaknessRunes["misguided thief"] = 3161
monsterWeaknessRunes["mitmah scout"] = 3175
monsterWeaknessRunes["mitmah seer"] = 3202
monsterWeaknessRunes["mitmah vanguard"] = 3202
monsterWeaknessRunes["modified gnarlhound"] = 3161
monsterWeaknessRunes["mole"] = 3191
monsterWeaknessRunes["monk"] = 3200
monsterWeaknessRunes["monk familiar"] = 3161
monsterWeaknessRunes["monk of the order"] = 3200
monsterWeaknessRunes["monk's apparition"] = 3155
monsterWeaknessRunes["monstor"] = 3202
monsterWeaknessRunes["mooh'tah warrior"] = 3202
monsterWeaknessRunes["moohtant"] = 3200
monsterWeaknessRunes["morgaroth"] = 3161
monsterWeaknessRunes["morguthis"] = 3175
monsterWeaknessRunes["morik the gladiator"] = 3155
monsterWeaknessRunes["mornenion"] = 3161
monsterWeaknessRunes["morshabaal"] = 3161
monsterWeaknessRunes["mould phantom"] = 3200
monsterWeaknessRunes["mountain troll"] = 3200
monsterWeaknessRunes["mounted thorn knight"] = 3155
monsterWeaknessRunes["mozradek"] = 3161
monsterWeaknessRunes["mr. punish"] = 3155
monsterWeaknessRunes["muddy earth elemental"] = 3191
monsterWeaknessRunes["muglex clan assassin"] = 3161
monsterWeaknessRunes["muglex clan footman"] = 3161
monsterWeaknessRunes["muglex clan scavenger"] = 3161
monsterWeaknessRunes["mummy"] = 3202
monsterWeaknessRunes["munster"] = 3161
monsterWeaknessRunes["murcion"] = 3161
monsterWeaknessRunes["mushroom"] = 3161
monsterWeaknessRunes["mushroom sniffer"] = 3161
monsterWeaknessRunes["mutated bat"] = 3161
monsterWeaknessRunes["mutated human"] = 3202
monsterWeaknessRunes["mutated rat"] = 3191
monsterWeaknessRunes["mutated tiger"] = 3155
monsterWeaknessRunes["mutated visco"] = 3191
monsterWeaknessRunes["mutated zalamon"] = 3202
monsterWeaknessRunes["mycobiontic beetle"] = 3161
monsterWeaknessRunes["naga archer"] = 3175
monsterWeaknessRunes["naga warrior"] = 3202
monsterWeaknessRunes["nargol the impaler"] = 3191
monsterWeaknessRunes["necromancer"] = 3191
monsterWeaknessRunes["necromancer servant"] = 3191
monsterWeaknessRunes["necromantic focus"] = 3161
monsterWeaknessRunes["necropharus"] = 3161
monsterWeaknessRunes["neferi the spy"] = 3161
monsterWeaknessRunes["neutral deepling warrior"] = 3202
monsterWeaknessRunes["nibblemaw"] = 3202
monsterWeaknessRunes["nightfiend"] = 3191
monsterWeaknessRunes["nighthunter"] = 3200
monsterWeaknessRunes["nightmare"] = 3200
monsterWeaknessRunes["nightmare of gaz'haragoth"] = 3161
monsterWeaknessRunes["nightmare scion"] = 3200
monsterWeaknessRunes["nightmare tendril"] = 3161
monsterWeaknessRunes["nightmarish dream"] = 3202
monsterWeaknessRunes["nightstalker"] = 3202
monsterWeaknessRunes["noble lion"] = 3161
monsterWeaknessRunes["nomad"] = 3161
monsterWeaknessRunes["nomad blue"] = 3161
monsterWeaknessRunes["nomad female"] = 3161
monsterWeaknessRunes["norgle glacierbeard"] = 3202
monsterWeaknessRunes["northern pike"] = 3202
monsterWeaknessRunes["novice of the cult"] = 3200
monsterWeaknessRunes["noxious ripptor"] = 3161
monsterWeaknessRunes["nymph"] = 3200
monsterWeaknessRunes["obujos"] = 3202
monsterWeaknessRunes["ocyakao"] = 3202
monsterWeaknessRunes["ogre brute"] = 3202
monsterWeaknessRunes["ogre rowdy"] = 3161
monsterWeaknessRunes["ogre ruffian"] = 3161
monsterWeaknessRunes["ogre sage"] = 3202
monsterWeaknessRunes["ogre savage"] = 3202
monsterWeaknessRunes["ogre shaman"] = 3200
monsterWeaknessRunes["old bear"] = 3161
monsterWeaknessRunes["old beholder"] = 3191
monsterWeaknessRunes["old bug"] = 3191
monsterWeaknessRunes["old giant spider"] = 3191
monsterWeaknessRunes["old pig"] = 3161
monsterWeaknessRunes["old spider"] = 3191
monsterWeaknessRunes["old wasp"] = 3191
monsterWeaknessRunes["old wolf"] = 3161
monsterWeaknessRunes["omnivora"] = 3191
monsterWeaknessRunes["omrafir"] = 3161
monsterWeaknessRunes["omruc"] = 3161
monsterWeaknessRunes["oozing carcass"] = 3175
monsterWeaknessRunes["oozing corpus"] = 3202
monsterWeaknessRunes["orc"] = 3175
monsterWeaknessRunes["orc armor"] = 3175
monsterWeaknessRunes["orc berserker"] = 3175
monsterWeaknessRunes["orc cult fanatic"] = 3175
monsterWeaknessRunes["orc cult inquisitor"] = 3175
monsterWeaknessRunes["orc cult minion"] = 3175
monsterWeaknessRunes["orc cult priest"] = 3175
monsterWeaknessRunes["orc cultist"] = 3175
monsterWeaknessRunes["orc helmet"] = 3175
monsterWeaknessRunes["orc leader"] = 3175
monsterWeaknessRunes["orc marauder"] = 3175
monsterWeaknessRunes["orc rider"] = 3175
monsterWeaknessRunes["orc sambackpack"] = 3175
monsterWeaknessRunes["orc shaman"] = 3175
monsterWeaknessRunes["orc shield"] = 3175
monsterWeaknessRunes["orc spearman"] = 3175
monsterWeaknessRunes["orc warlord"] = 3175
monsterWeaknessRunes["orc warrior"] = 3175
monsterWeaknessRunes["orchid frog"] = 3191
monsterWeaknessRunes["orclops doomhauler"] = 3161
monsterWeaknessRunes["orclops ravager"] = 3202
monsterWeaknessRunes["orcus the cruel"] = 3175
monsterWeaknessRunes["orewalker"] = 3202
monsterWeaknessRunes["organic matter"] = 3161
monsterWeaknessRunes["orshabaal"] = 3161
monsterWeaknessRunes["outburst"] = 3202
monsterWeaknessRunes["overcharge"] = 3161
monsterWeaknessRunes["overcharged demon"] = 3161
monsterWeaknessRunes["overcharged disruption"] = 3161
monsterWeaknessRunes["overcharged energy elemental"] = 3175
monsterWeaknessRunes["paiz the pauperizer"] = 3161
monsterWeaknessRunes["paladin familiar"] = 3161
monsterWeaknessRunes["paladin's apparition"] = 3155
monsterWeaknessRunes["panda"] = 3191
monsterWeaknessRunes["parasite"] = 3161
monsterWeaknessRunes["parder"] = 3191
monsterWeaknessRunes["parrot"] = 3161
monsterWeaknessRunes["party skeleton"] = 3161
monsterWeaknessRunes["penguin"] = 3202
monsterWeaknessRunes["percht"] = 3161
monsterWeaknessRunes["percht minion"] = 3161
monsterWeaknessRunes["phantasm"] = 3202
monsterWeaknessRunes["phantasm summon"] = 3202
monsterWeaknessRunes["pig"] = 3161
monsterWeaknessRunes["pigeon"] = 3175
monsterWeaknessRunes["pillar of death"] = 3161
monsterWeaknessRunes["pillar of draining"] = 3161
monsterWeaknessRunes["pillar of healing"] = 3161
monsterWeaknessRunes["pillar of protection"] = 3161
monsterWeaknessRunes["pillar of summoning"] = 3161
monsterWeaknessRunes["pink butterfly"] = 3161
monsterWeaknessRunes["pirat bombardier"] = 3175
monsterWeaknessRunes["pirat cutthroat"] = 3175
monsterWeaknessRunes["pirat mate"] = 3175
monsterWeaknessRunes["pirat scoundrel"] = 3175
monsterWeaknessRunes["pirate buccaneer"] = 3161
monsterWeaknessRunes["pirate corsair"] = 3191
monsterWeaknessRunes["pirate cutthroat"] = 3161
monsterWeaknessRunes["pirate ghost"] = 3161
monsterWeaknessRunes["pirate marauder"] = 3191
monsterWeaknessRunes["pirate skeleton"] = 3161
monsterWeaknessRunes["pixie"] = 3191
monsterWeaknessRunes["plagirath"] = 3191
monsterWeaknessRunes["plagueroot"] = 3191
monsterWeaknessRunes["plaguesmith"] = 3202
monsterWeaknessRunes["plant abomination"] = 3161
monsterWeaknessRunes["plant attendant"] = 3161
monsterWeaknessRunes["plunder patriarch"] = 3161
monsterWeaknessRunes["poacher"] = 3161
monsterWeaknessRunes["poison spider"] = 3191
monsterWeaknessRunes["poisonous carnisylvan"] = 3191
monsterWeaknessRunes["polar bear"] = 3155
monsterWeaknessRunes["poodle"] = 3161
monsterWeaknessRunes["pooka"] = 3202
monsterWeaknessRunes["possessed tree"] = 3161
monsterWeaknessRunes["powerful soul"] = 3161
monsterWeaknessRunes["preceptor lazare"] = 3200
monsterWeaknessRunes["priestess"] = 3200
monsterWeaknessRunes["priestess of the wild sun"] = 3161
monsterWeaknessRunes["primitive"] = 3161
monsterWeaknessRunes["prince drazzak"] = 3161
monsterWeaknessRunes["professor maxxen"] = 3161
monsterWeaknessRunes["psychic spirit elemental"] = 3191
monsterWeaknessRunes["purple butterfly"] = 3161
monsterWeaknessRunes["putrid mummy"] = 3191
monsterWeaknessRunes["pythius the rotten"] = 3161
monsterWeaknessRunes["quara constrictor"] = 3202
monsterWeaknessRunes["quara constrictor scout"] = 3202
monsterWeaknessRunes["quara hydromancer"] = 3202
monsterWeaknessRunes["quara hydromancer scout"] = 3202
monsterWeaknessRunes["quara looter"] = 3202
monsterWeaknessRunes["quara mantassin"] = 3202
monsterWeaknessRunes["quara mantassin scout"] = 3202
monsterWeaknessRunes["quara pincher"] = 3202
monsterWeaknessRunes["quara pincher scout"] = 3202
monsterWeaknessRunes["quara plunderer"] = 3202
monsterWeaknessRunes["quara predator"] = 3202
monsterWeaknessRunes["quara predator scout"] = 3202
monsterWeaknessRunes["quara raider"] = 3175
monsterWeaknessRunes["rabbit"] = 3161
monsterWeaknessRunes["rage of mazoran"] = 3161
monsterWeaknessRunes["rage squid"] = 3161
monsterWeaknessRunes["ragiaz"] = 3161
monsterWeaknessRunes["raging fire"] = 3161
monsterWeaknessRunes["raging mage"] = 3200
monsterWeaknessRunes["rahemos"] = 3200
monsterWeaknessRunes["rat"] = 3161
monsterWeaknessRunes["ratmiral blackwhiskers"] = 3161
monsterWeaknessRunes["ravenous beyondling"] = 3161
monsterWeaknessRunes["ravenous hunger"] = 3161
monsterWeaknessRunes["ravenous lava lurker"] = 3161
monsterWeaknessRunes["raxias"] = 3161
monsterWeaknessRunes["razzagorn"] = 3161
monsterWeaknessRunes["reality reaver"] = 3175
monsterWeaknessRunes["realityquake"] = 3161
monsterWeaknessRunes["red butterfly"] = 3161
monsterWeaknessRunes["redeemed soul"] = 3161
monsterWeaknessRunes["reflection of mawhawk"] = 3161
monsterWeaknessRunes["reflection of obujos"] = 3161
monsterWeaknessRunes["regenerating mass"] = 3191
monsterWeaknessRunes["renegade knight"] = 3155
monsterWeaknessRunes["renegade orc"] = 3175
monsterWeaknessRunes["renegade quara constrictor"] = 3202
monsterWeaknessRunes["renegade quara hydromancer"] = 3202
monsterWeaknessRunes["renegade quara mantassin"] = 3202
monsterWeaknessRunes["renegade quara pincher"] = 3202
monsterWeaknessRunes["renegade quara predator"] = 3202
monsterWeaknessRunes["retainer of baeloc"] = 3161
monsterWeaknessRunes["retching horror"] = 3202
monsterWeaknessRunes["rewar the bloody"] = 3191
monsterWeaknessRunes["rhindeer"] = 3191
monsterWeaknessRunes["ribstride"] = 3191
monsterWeaknessRunes["rift breacher"] = 3161
monsterWeaknessRunes["rift brood"] = 3155
monsterWeaknessRunes["rift fragment"] = 3161
monsterWeaknessRunes["rift invader"] = 3202
monsterWeaknessRunes["rift lord"] = 3161
monsterWeaknessRunes["rift minion"] = 3161
monsterWeaknessRunes["rift phantom"] = 3161
monsterWeaknessRunes["rift scythe"] = 3202
monsterWeaknessRunes["rift spawn"] = 3161
monsterWeaknessRunes["rift worm"] = 3175
monsterWeaknessRunes["ripper spectre"] = 3191
monsterWeaknessRunes["risen soldier"] = 3161
monsterWeaknessRunes["roaring lion"] = 3161
monsterWeaknessRunes["roaring water elemental"] = 3202
monsterWeaknessRunes["robby the reckless"] = 3161
monsterWeaknessRunes["rocko"] = 3200
monsterWeaknessRunes["rocky"] = 3191
monsterWeaknessRunes["rogue naga"] = 3161
monsterWeaknessRunes["ron the ripper"] = 3161
monsterWeaknessRunes["rootthing amber shaper"] = 3161
monsterWeaknessRunes["rootthing bug tracker"] = 3191
monsterWeaknessRunes["rootthing nutshell"] = 3191
monsterWeaknessRunes["rorc"] = 3175
monsterWeaknessRunes["rot elemental"] = 3202
monsterWeaknessRunes["rotten golem"] = 3191
monsterWeaknessRunes["rotten man-maggot"] = 3175
monsterWeaknessRunes["rottie the rotworm"] = 3161
monsterWeaknessRunes["rotworm"] = 3161
monsterWeaknessRunes["rotworm queen"] = 3191
monsterWeaknessRunes["rukor zad"] = 3161
monsterWeaknessRunes["rupture"] = 3161
monsterWeaknessRunes["rustheap golem"] = 3202
monsterWeaknessRunes["sabretooth"] = 3161
monsterWeaknessRunes["sacred snake"] = 3161
monsterWeaknessRunes["sacred spider"] = 3191
monsterWeaknessRunes["salamander"] = 3161
monsterWeaknessRunes["salamander trainer"] = 3161
monsterWeaknessRunes["sand brood"] = 3161
monsterWeaknessRunes["sand vortex"] = 3161
monsterWeaknessRunes["sandcrawler"] = 3191
monsterWeaknessRunes["sandstone scorpion"] = 3161
monsterWeaknessRunes["scar tribe shaman"] = 3161
monsterWeaknessRunes["scar tribe warrior"] = 3161
monsterWeaknessRunes["scarab"] = 3191
monsterWeaknessRunes["scarlett etzel"] = 3161
monsterWeaknessRunes["schiach"] = 3191
monsterWeaknessRunes["scorn of the emperor"] = 3202
monsterWeaknessRunes["scorpion"] = 3161
monsterWeaknessRunes["sea serpent"] = 3200
monsterWeaknessRunes["seacrest serpent"] = 3202
monsterWeaknessRunes["seagull"] = 3161
monsterWeaknessRunes["security golem"] = 3202
monsterWeaknessRunes["serpent spawn"] = 3202
monsterWeaknessRunes["shaburak demon"] = 3175
monsterWeaknessRunes["shaburak lord"] = 3175
monsterWeaknessRunes["shaburak prince"] = 3175
monsterWeaknessRunes["shadow fiend"] = 3191
monsterWeaknessRunes["shadow hound"] = 3191
monsterWeaknessRunes["shadow pupil"] = 3191
monsterWeaknessRunes["shadow tentacle"] = 3200
monsterWeaknessRunes["shadowpelt"] = 3191
monsterWeaknessRunes["shaper matriarch"] = 3202
monsterWeaknessRunes["shard of corruption"] = 3161
monsterWeaknessRunes["shard of magnor"] = 3161
monsterWeaknessRunes["shardhead"] = 3202
monsterWeaknessRunes["shark"] = 3202
monsterWeaknessRunes["sharpclaw"] = 3191
monsterWeaknessRunes["sharptooth"] = 3202
monsterWeaknessRunes["sheep"] = 3191
monsterWeaknessRunes["shiversleep"] = 3202
monsterWeaknessRunes["shock head"] = 3202
monsterWeaknessRunes["shrieking cry-stal"] = 3175
monsterWeaknessRunes["shulgrax"] = 3202
monsterWeaknessRunes["sibang"] = 3161
monsterWeaknessRunes["sight of surrender"] = 3202
monsterWeaknessRunes["silencer"] = 3200
monsterWeaknessRunes["silver rabbit"] = 3161
monsterWeaknessRunes["sineater inferniarch"] = 3202
monsterWeaknessRunes["sir baeloc"] = 3191
monsterWeaknessRunes["sir nictros"] = 3191
monsterWeaknessRunes["sir valorcrest"] = 3202
monsterWeaknessRunes["sister hetai"] = 3161
monsterWeaknessRunes["skeleton"] = 3161
monsterWeaknessRunes["skeleton elite warrior"] = 3202
monsterWeaknessRunes["skeleton warrior"] = 3161
monsterWeaknessRunes["skunk"] = 3161
monsterWeaknessRunes["slick water elemental"] = 3202
monsterWeaknessRunes["slim"] = 3191
monsterWeaknessRunes["slime"] = 3202
monsterWeaknessRunes["slug"] = 3191
monsterWeaknessRunes["smuggler"] = 3155
monsterWeaknessRunes["smuggler baron silvertoe"] = 3161
monsterWeaknessRunes["snail slime"] = 3202
monsterWeaknessRunes["snake"] = 3161
monsterWeaknessRunes["snake god essence"] = 3202
monsterWeaknessRunes["snake thing"] = 3202
monsterWeaknessRunes["somewhat beatable"] = 3161
monsterWeaknessRunes["son of verminor"] = 3161
monsterWeaknessRunes["sopping carcass"] = 3175
monsterWeaknessRunes["sopping corpus"] = 3202
monsterWeaknessRunes["sorcerer familiar"] = 3161
monsterWeaknessRunes["sorcerer's apparition"] = 3191
monsterWeaknessRunes["soul cage"] = 3161
monsterWeaknessRunes["soul of dragonking zyrtarch"] = 3161
monsterWeaknessRunes["soul reaper"] = 3161
monsterWeaknessRunes["soul scourge"] = 3161
monsterWeaknessRunes["soul sphere"] = 3161
monsterWeaknessRunes["soul-broken harbinger"] = 3191
monsterWeaknessRunes["soulcatcher"] = 3161
monsterWeaknessRunes["souleater"] = 3202
monsterWeaknessRunes["soulless minion"] = 3191
monsterWeaknessRunes["soulsnatcher"] = 3161
monsterWeaknessRunes["spark of destruction"] = 3161
monsterWeaknessRunes["sparkion"] = 3175
monsterWeaknessRunes["spawn of havoc"] = 3161
monsterWeaknessRunes["spawn of the welter"] = 3202
monsterWeaknessRunes["spectre"] = 3202
monsterWeaknessRunes["spellreaper inferniarch"] = 3175
monsterWeaknessRunes["sphere of wrath"] = 3200
monsterWeaknessRunes["sphinx"] = 3155
monsterWeaknessRunes["spider"] = 3191
monsterWeaknessRunes["spidris"] = 3202
monsterWeaknessRunes["spidris elite"] = 3202
monsterWeaknessRunes["spidris elite summon"] = 3161
monsterWeaknessRunes["spiky carnivor"] = 3191
monsterWeaknessRunes["spirit of earth"] = 3161
monsterWeaknessRunes["spirit of fertility"] = 3161
monsterWeaknessRunes["spirit of fire"] = 3161
monsterWeaknessRunes["spirit of water"] = 3202
monsterWeaknessRunes["spirit overlord"] = 3161
monsterWeaknessRunes["spit nettle"] = 3191
monsterWeaknessRunes["spite of the emperor"] = 3202
monsterWeaknessRunes["spiteful spitter"] = 3161
monsterWeaknessRunes["spitter"] = 3202
monsterWeaknessRunes["splasher"] = 3202
monsterWeaknessRunes["spyrat east"] = 3175
monsterWeaknessRunes["spyrat north"] = 3175
monsterWeaknessRunes["spyrat south"] = 3175
monsterWeaknessRunes["spyrat west"] = 3175
monsterWeaknessRunes["squid warden"] = 3191
monsterWeaknessRunes["squidgy slime"] = 3202
monsterWeaknessRunes["squire of nictros"] = 3161
monsterWeaknessRunes["squirrel"] = 3161
monsterWeaknessRunes["srezz yellow eyes"] = 3161
monsterWeaknessRunes["stabilizing dread intruder"] = 3200
monsterWeaknessRunes["stabilizing reality reaver"] = 3175
monsterWeaknessRunes["stalker"] = 3200
monsterWeaknessRunes["stalking stalk"] = 3200
monsterWeaknessRunes["stampor"] = 3175
monsterWeaknessRunes["starving wolf"] = 3161
monsterWeaknessRunes["stolen knowledge of armor"] = 3161
monsterWeaknessRunes["stolen knowledge of healing"] = 3161
monsterWeaknessRunes["stolen knowledge of lifesteal"] = 3161
monsterWeaknessRunes["stolen knowledge of spells"] = 3161
monsterWeaknessRunes["stolen knowledge of summoning"] = 3161
monsterWeaknessRunes["stolen soul"] = 3161
monsterWeaknessRunes["stolen tome of portals"] = 3191
monsterWeaknessRunes["stone devourer"] = 3191
monsterWeaknessRunes["stone golem"] = 3161
monsterWeaknessRunes["stone rhino"] = 3202
monsterWeaknessRunes["stonecracker"] = 3161
monsterWeaknessRunes["stonerefiner"] = 3161
monsterWeaknessRunes["strange slime"] = 3161
monsterWeaknessRunes["streaked devourer"] = 3161
monsterWeaknessRunes["strong glooth horror"] = 3161
monsterWeaknessRunes["strong soul"] = 3161
monsterWeaknessRunes["sugar cube"] = 3202
monsterWeaknessRunes["sugar cube worker"] = 3202
monsterWeaknessRunes["sugar daddy"] = 3191
monsterWeaknessRunes["sugar mommy"] = 3191
monsterWeaknessRunes["sulphider"] = 3161
monsterWeaknessRunes["sulphur scuttler"] = 3191
monsterWeaknessRunes["sulphur spouter"] = 3161
monsterWeaknessRunes["sun-marked goanna"] = 3161
monsterWeaknessRunes["supercharged mazzinor"] = 3161
monsterWeaknessRunes["superior death minion"] = 3161
monsterWeaknessRunes["svoren the mad"] = 3155
monsterWeaknessRunes["swamp troll"] = 3191
monsterWeaknessRunes["swampling"] = 3161
monsterWeaknessRunes["swan maiden"] = 3191
monsterWeaknessRunes["swarmer"] = 3191
monsterWeaknessRunes["swarmer hatchling"] = 3161
monsterWeaknessRunes["sword of vengeance"] = 3161
monsterWeaknessRunes["symbol of hatred"] = 3161
monsterWeaknessRunes["tainted soul"] = 3161
monsterWeaknessRunes["tainted soul splinter"] = 3161
monsterWeaknessRunes["tame terror bird"] = 3161
monsterWeaknessRunes["tanjis"] = 3175
monsterWeaknessRunes["tarantula"] = 3191
monsterWeaknessRunes["tarbaz"] = 3161
monsterWeaknessRunes["tarnished spirit"] = 3161
monsterWeaknessRunes["tazhadur"] = 3161
monsterWeaknessRunes["teleskor"] = 3161
monsterWeaknessRunes["tentacle of the deep terror"] = 3161
monsterWeaknessRunes["tentugly's head"] = 3175
monsterWeaknessRunes["terofar"] = 3200
monsterWeaknessRunes["terramite"] = 3191
monsterWeaknessRunes["terrified elephant"] = 3202
monsterWeaknessRunes["terror bird"] = 3191
monsterWeaknessRunes["terrorsleep"] = 3202
monsterWeaknessRunes["thalas"] = 3191
monsterWeaknessRunes["thanatursus"] = 3155
monsterWeaknessRunes["thawing dragon lord"] = 3161
monsterWeaknessRunes["the abomination"] = 3161
monsterWeaknessRunes["the armored voidborn"] = 3161
monsterWeaknessRunes["the astral source"] = 3202
monsterWeaknessRunes["the axeorcist"] = 3202
monsterWeaknessRunes["the baron from below"] = 3161
monsterWeaknessRunes["the blazing rose"] = 3161
monsterWeaknessRunes["the blazing time guardian"] = 3191
monsterWeaknessRunes["the blightfather"] = 3161
monsterWeaknessRunes["the bloodtusk"] = 3161
monsterWeaknessRunes["the bloodweb"] = 3202
monsterWeaknessRunes["the book of death"] = 3191
monsterWeaknessRunes["the book of secrets"] = 3161
monsterWeaknessRunes["the brainstealer"] = 3161
monsterWeaknessRunes["the cold of winter"] = 3161
monsterWeaknessRunes["the collector"] = 3202
monsterWeaknessRunes["the count"] = 3161
monsterWeaknessRunes["the count of the core"] = 3161
monsterWeaknessRunes["the dark dancer"] = 3161
monsterWeaknessRunes["the destruction"] = 3202
monsterWeaknessRunes["the devourer of secrets"] = 3161
monsterWeaknessRunes["the diamond blossom"] = 3161
monsterWeaknessRunes["the distorted astral source"] = 3161
monsterWeaknessRunes["the dread maiden"] = 3191
monsterWeaknessRunes["the dreadorian"] = 3161
monsterWeaknessRunes["the duke of the depths"] = 3161
monsterWeaknessRunes["the end of days"] = 3161
monsterWeaknessRunes["the enraged thorn knight"] = 3155
monsterWeaknessRunes["the evil eye"] = 3161
monsterWeaknessRunes["the false god"] = 3161
monsterWeaknessRunes["the fear feaster"] = 3202
monsterWeaknessRunes["the first dragon"] = 3161
monsterWeaknessRunes["the flaming orchid"] = 3161
monsterWeaknessRunes["the freezing time guardian"] = 3161
monsterWeaknessRunes["the frog prince"] = 3155
monsterWeaknessRunes["the hag"] = 3175
monsterWeaknessRunes["the hairy one"] = 3191
monsterWeaknessRunes["the handmaiden"] = 3200
monsterWeaknessRunes["the heat of summer"] = 3161
monsterWeaknessRunes["the horned fox"] = 3161
monsterWeaknessRunes["the hunger"] = 3191
monsterWeaknessRunes["the imperor"] = 3161
monsterWeaknessRunes["the keeper"] = 3202
monsterWeaknessRunes["the last lore keeper"] = 3161
monsterWeaknessRunes["the lily of night"] = 3161
monsterWeaknessRunes["the lord of the lice"] = 3161
monsterWeaknessRunes["the many"] = 3202
monsterWeaknessRunes["the masked marauder"] = 3161
monsterWeaknessRunes["the monster"] = 3161
monsterWeaknessRunes["the mutated pumpkin"] = 3161
monsterWeaknessRunes["the nightmare beast"] = 3161
monsterWeaknessRunes["the noxious spawn"] = 3202
monsterWeaknessRunes["the obliverator"] = 3161
monsterWeaknessRunes["the old widow"] = 3161
monsterWeaknessRunes["the pale count"] = 3175
monsterWeaknessRunes["the pale worm"] = 3161
monsterWeaknessRunes["the percht queen"] = 3161
monsterWeaknessRunes["the pit lord"] = 3161
monsterWeaknessRunes["the plasmother"] = 3155
monsterWeaknessRunes["the primal menace"] = 3202
monsterWeaknessRunes["the rage"] = 3161
monsterWeaknessRunes["the ravager"] = 3191
monsterWeaknessRunes["the rootkraken"] = 3191
monsterWeaknessRunes["the sandking"] = 3161
monsterWeaknessRunes["the sandking fake"] = 3161
monsterWeaknessRunes["the scion of havoc"] = 3161
monsterWeaknessRunes["the scourge of oblivion"] = 3161
monsterWeaknessRunes["the shatterer"] = 3161
monsterWeaknessRunes["the shielded thorn knight"] = 3155
monsterWeaknessRunes["the sinister hermit"] = 3161
monsterWeaknessRunes["the snapper"] = 3191
monsterWeaknessRunes["the souldespoiler"] = 3161
monsterWeaknessRunes["the source of corruption"] = 3161
monsterWeaknessRunes["the spellstealer"] = 3161
monsterWeaknessRunes["the time guardian"] = 3200
monsterWeaknessRunes["the unarmored voidborn"] = 3161
monsterWeaknessRunes["the unwelcome"] = 3161
monsterWeaknessRunes["the voice of ruin"] = 3161
monsterWeaknessRunes["the weakened count"] = 3191
monsterWeaknessRunes["the welter"] = 3202
monsterWeaknessRunes["thieving squirrel"] = 3161
monsterWeaknessRunes["thorn minion"] = 3161
monsterWeaknessRunes["thorn steed"] = 3155
monsterWeaknessRunes["thornback tortoise"] = 3191
monsterWeaknessRunes["thornfire wolf"] = 3161
monsterWeaknessRunes["thul"] = 3202
monsterWeaknessRunes["tiger"] = 3161
monsterWeaknessRunes["time keeper"] = 3161
monsterWeaknessRunes["timira the many-headed"] = 3175
monsterWeaknessRunes["tiquandas revenge"] = 3191
monsterWeaknessRunes["tirecz"] = 3200
monsterWeaknessRunes["toad"] = 3191
monsterWeaknessRunes["tomb servant"] = 3161
monsterWeaknessRunes["tormented ghost"] = 3202
monsterWeaknessRunes["tormentor"] = 3200
monsterWeaknessRunes["tortoise"] = 3191
monsterWeaknessRunes["training machine"] = 3161
monsterWeaknessRunes["travelling merchant"] = 3155
monsterWeaknessRunes["tremendous tyrant"] = 3175
monsterWeaknessRunes["tremor worm"] = 3161
monsterWeaknessRunes["tremorak"] = 3191
monsterWeaknessRunes["troll"] = 3175
monsterWeaknessRunes["troll champion"] = 3175
monsterWeaknessRunes["troll guard"] = 3175
monsterWeaknessRunes["troll legionnaire"] = 3161
monsterWeaknessRunes["troll marauder"] = 3200
monsterWeaknessRunes["troll-trained salamander"] = 3161
monsterWeaknessRunes["tromphonyte"] = 3161
monsterWeaknessRunes["true dawnfire asura"] = 3202
monsterWeaknessRunes["true frost flower asura"] = 3202
monsterWeaknessRunes["true midnight asura"] = 3202
monsterWeaknessRunes["truffle"] = 3191
monsterWeaknessRunes["truffle cook"] = 3161
monsterWeaknessRunes["tunnel tyrant"] = 3161
monsterWeaknessRunes["turbulent elemental"] = 3191
monsterWeaknessRunes["twisted pooka"] = 3202
monsterWeaknessRunes["twisted shaper"] = 3202
monsterWeaknessRunes["two-headed turtle"] = 3175
monsterWeaknessRunes["tyrn"] = 3161
monsterWeaknessRunes["ugly monster"] = 3200
monsterWeaknessRunes["unaz the mean"] = 3161
monsterWeaknessRunes["unbound blightwalker"] = 3200
monsterWeaknessRunes["unbound defiler"] = 3191
monsterWeaknessRunes["unbound demon"] = 3161
monsterWeaknessRunes["unbound demon outcast"] = 3202
monsterWeaknessRunes["unchained fire"] = 3161
monsterWeaknessRunes["undead cavebear"] = 3161
monsterWeaknessRunes["undead dragon"] = 3202
monsterWeaknessRunes["undead elite gladiator"] = 3175
monsterWeaknessRunes["undead gladiator"] = 3175
monsterWeaknessRunes["undead mine worker"] = 3161
monsterWeaknessRunes["undead minion"] = 3161
monsterWeaknessRunes["undead prospector"] = 3191
monsterWeaknessRunes["undertaker"] = 3200
monsterWeaknessRunes["ungreez"] = 3161
monsterWeaknessRunes["unpleasant dream"] = 3161
monsterWeaknessRunes["unstable spark"] = 3161
monsterWeaknessRunes["urmahlullu the immaculate"] = 3161
monsterWeaknessRunes["urmahlullu the tamed"] = 3161
monsterWeaknessRunes["urmahlullu the weakened"] = 3161
monsterWeaknessRunes["ushuriel"] = 3161
monsterWeaknessRunes["usurper archer"] = 3155
monsterWeaknessRunes["usurper commander"] = 3155
monsterWeaknessRunes["usurper knight"] = 3155
monsterWeaknessRunes["usurper warlock"] = 3155
monsterWeaknessRunes["utua stone sting"] = 3161
monsterWeaknessRunes["valkyrie"] = 3200
monsterWeaknessRunes["vampire"] = 3191
monsterWeaknessRunes["vampire bride"] = 3191
monsterWeaknessRunes["vampire pig"] = 3161
monsterWeaknessRunes["vampire viscount"] = 3191
monsterWeaknessRunes["vampiric blood"] = 3161
monsterWeaknessRunes["varnished diremaw"] = 3175
monsterWeaknessRunes["vashresamun"] = 3175
monsterWeaknessRunes["vemiath"] = 3161
monsterWeaknessRunes["venerable girtablilu"] = 3202
monsterWeaknessRunes["vermin swarm"] = 3191
monsterWeaknessRunes["verminor"] = 3161
monsterWeaknessRunes["versperoth"] = 3175
monsterWeaknessRunes["vexclaw"] = 3161
monsterWeaknessRunes["vibrant phantom"] = 3175
monsterWeaknessRunes["vicious manbat"] = 3191
monsterWeaknessRunes["vicious squire"] = 3155
monsterWeaknessRunes["vile grandmaster"] = 3155
monsterWeaknessRunes["voidshard"] = 3161
monsterWeaknessRunes["vok the freakish"] = 3161
monsterWeaknessRunes["vulcongra"] = 3161
monsterWeaknessRunes["wailing widow"] = 3191
monsterWeaknessRunes["walker"] = 3202
monsterWeaknessRunes["walking pillar"] = 3191
monsterWeaknessRunes["wandering pillar"] = 3191
monsterWeaknessRunes["war golem"] = 3202
monsterWeaknessRunes["war servant"] = 3161
monsterWeaknessRunes["war wolf"] = 3161
monsterWeaknessRunes["wardragon"] = 3161
monsterWeaknessRunes["warlock"] = 3200
monsterWeaknessRunes["warlord ruzad"] = 3175
monsterWeaknessRunes["warm fire"] = 3161
monsterWeaknessRunes["wasp"] = 3191
monsterWeaknessRunes["waspoid"] = 3191
monsterWeaknessRunes["water buffalo"] = 3161
monsterWeaknessRunes["water elemental"] = 3202
monsterWeaknessRunes["weak soul"] = 3161
monsterWeaknessRunes["weakened demon"] = 3161
monsterWeaknessRunes["weakened frazzlemaw"] = 3161
monsterWeaknessRunes["weakened glooth horror"] = 3161
monsterWeaknessRunes["weakened shlorg"] = 3161
monsterWeaknessRunes["webster"] = 3202
monsterWeaknessRunes["weeper"] = 3161
monsterWeaknessRunes["weeping soul"] = 3161
monsterWeaknessRunes["werebadger"] = 3161
monsterWeaknessRunes["werebear"] = 3191
monsterWeaknessRunes["wereboar"] = 3191
monsterWeaknessRunes["werecrocodile"] = 3161
monsterWeaknessRunes["werefox"] = 3191
monsterWeaknessRunes["werehyaena"] = 3161
monsterWeaknessRunes["werehyaena shaman"] = 3161
monsterWeaknessRunes["werelion"] = 3161
monsterWeaknessRunes["werelioness"] = 3161
monsterWeaknessRunes["werepanther"] = 3161
monsterWeaknessRunes["weretiger"] = 3191
monsterWeaknessRunes["werewolf"] = 3161
monsterWeaknessRunes["white deer"] = 3161
monsterWeaknessRunes["white lion"] = 3161
monsterWeaknessRunes["white pale"] = 3161
monsterWeaknessRunes["white shade"] = 3161
monsterWeaknessRunes["white tiger"] = 3161
monsterWeaknessRunes["white weretiger"] = 3175
monsterWeaknessRunes["wiggler"] = 3191
monsterWeaknessRunes["wild dog"] = 3161
monsterWeaknessRunes["wild horse"] = 3161
monsterWeaknessRunes["wild knowledge"] = 3175
monsterWeaknessRunes["wild warrior"] = 3155
monsterWeaknessRunes["wildness of urmahlullu"] = 3161
monsterWeaknessRunes["willi wasp"] = 3191
monsterWeaknessRunes["wilting leaf golem"] = 3161
monsterWeaknessRunes["wine cask"] = 3191
monsterWeaknessRunes["winter wolf"] = 3155
monsterWeaknessRunes["wisdom of urmahlullu"] = 3161
monsterWeaknessRunes["wisp"] = 3161
monsterWeaknessRunes["witch"] = 3155
monsterWeaknessRunes["wolf"] = 3161
monsterWeaknessRunes["woodling"] = 3161
monsterWeaknessRunes["worker golem"] = 3202
monsterWeaknessRunes["world devourer"] = 3161
monsterWeaknessRunes["worm priestess"] = 3202
monsterWeaknessRunes["wormling"] = 3161
monsterWeaknessRunes["wrath of the emperor"] = 3202
monsterWeaknessRunes["wyrm"] = 3161
monsterWeaknessRunes["wyvern"] = 3191
monsterWeaknessRunes["xenia"] = 3161
monsterWeaknessRunes["xogixath"] = 3161
monsterWeaknessRunes["yaga the crone"] = 3155
monsterWeaknessRunes["yakchal"] = 3202
monsterWeaknessRunes["yalahari"] = 3161
monsterWeaknessRunes["yalahari despoiler"] = 3161
monsterWeaknessRunes["yellow butterfly"] = 3161
monsterWeaknessRunes["yeti"] = 3191
monsterWeaknessRunes["yielothax"] = 3200
monsterWeaknessRunes["yirkas blue scales"] = 3161
monsterWeaknessRunes["young goanna"] = 3202
monsterWeaknessRunes["young sea serpent"] = 3200
monsterWeaknessRunes["young troll"] = 3175
monsterWeaknessRunes["zamulosh"] = 3175
monsterWeaknessRunes["zamulosh2"] = 3175
monsterWeaknessRunes["zamulosh3"] = 3200
monsterWeaknessRunes["zanakeph"] = 3202
monsterWeaknessRunes["zarabustor"] = 3200
monsterWeaknessRunes["zarcorix of yalahar"] = 3161
monsterWeaknessRunes["zavarash"] = 3200
monsterWeaknessRunes["zevelon duskbringer"] = 3161
monsterWeaknessRunes["zomba"] = 3161
monsterWeaknessRunes["zombie"] = 3200
monsterWeaknessRunes["zoralurk"] = 3161
monsterWeaknessRunes["zorvorax"] = 3202
monsterWeaknessRunes["zugurosh"] = 3161
monsterWeaknessRunes["zulazza the corruptor"] = 3191
monsterWeaknessRunes["zushuka"] = 3202